version: "3"

tasks:
  deploy:
    dir: .
    cmds:
      - npx wrangler deploy

  env-sample:
    dir: .
    cmds:
      - |
          cat .env .env.prod 2>/dev/null \
            | grep -E '^[A-Z_]+=' \
            | cut -d'=' -f1 \
            | sort -u \
            | sed 's/$/=""/' \
            > .env.sample

  env-prod:
    dir: .
    cmds:
      - |
          grep -v '^#' ./.env.prod | grep '=' | while IFS='=' read -r key value; do
            echo "$value" | npx wrangler secret put "$key" --config ./wrangler.json
          done
