version: "3"

tasks:
  deploy:
    dir: .
    cmds:
      - npx wrangler deploy

  env-sample:
    dir: .
    cmds:
      - sed -E '/^[A-Z_][A-Z0-9_]*=/s/=.*/=""/' .env > .env.sample

  env-prod:
    dir: .
    cmds:
      - |
          grep -v '^#' ./.env.prod | grep '=' | while IFS='=' read -r key value; do
            echo "$value" | npx wrangler secret put "$key" --config ./wrangler.json
          done
