# https://github.com/tauri-apps/tauri-action/blob/3013cac/examples/test-build-only.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/desktop/**
      - plugins/**
  pull_request:
    branches:
      - main
    paths:
      - apps/desktop/**
      - plugins/**
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos"
            runner: "macos-14"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm_install
      - uses: denoland/setup-deno@v1
      - run: pnpm -F ui build
      - run: pnpm -r typecheck
      - run: pnpm -r test
      - uses: ./.github/actions/install_desktop_deps
        with:
          target: ${{ matrix.platform }}
      - uses: ./.github/actions/rust_install
        with:
          target: ${{ matrix.platform }}
      - run: cargo check -p desktop
