# https://docs.crabnebula.dev/cloud/ci/tauri-v2-workflow/
on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CN_APPLICATION: "fastrepl/hyprnote"
  RELEASE_CHANNEL: ${{ (github.event_name == 'release' && github.event.release.tag_name != '') && 'nightly' || (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/')) && 'stable' || 'staging' }}
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'desktop_')) }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos"
            target: "aarch64-apple-darwin"
            runner: "macos-14"
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - if: ${{ env.RELEASE_CHANNEL != 'staging' }}
        run: |
          VERSION=$(jq -r '.version' ./apps/desktop/src-tauri/tauri.conf.json)

          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
            echo "Version: $VERSION, Tag name: $TAG_NAME"
            if [[ ! "$TAG_NAME" == *"$VERSION"* ]]; then
              exit 1
            fi
          fi
        shell: bash
      - if: ${{ env.RELEASE_CHANNEL != 'staging' }}
        uses: ./.github/actions/cn_release
        with:
          cmd: draft
          app: ${{ env.CN_APPLICATION }}
          key: ${{ secrets.CN_API_KEY }}
          channel: ${{ env.RELEASE_CHANNEL }}
          framework: tauri
          working-directory: ./apps/desktop
      - uses: ./.github/actions/install_desktop_deps
        with:
          target: ${{ matrix.platform }}
      - uses: ./.github/actions/rust_install
        with:
          platform: ${{ matrix.platform }}
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - uses: ./.github/actions/apple_cert
        id: apple-cert
        if: ${{ matrix.platform == 'macos' }}
        with:
          apple-certificate: ${{ secrets.APPLE_CERTIFICATE }}
          apple-certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      - run: |
          FEATURES_FLAG=""
          if [[ "${{ env.RELEASE_CHANNEL }}" == "staging" ]]; then
            FEATURES_FLAG="--features devtools"
          fi
          pnpm -F desktop tauri build --target ${{ matrix.target }} --verbose $FEATURES_FLAG
        env:
          # https://github.com/tauri-apps/tauri-action/issues/740
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AM_API_KEY: ${{ secrets.AM_API_KEY }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      - run: |
          mkdir -p target/release/
          find target/${{ matrix.target }}/release -type f -not -path "*/\.*" -exec cp {} target/release/ \;
        shell: bash
        working-directory: ./apps/desktop/src-tauri
      - if: ${{ env.RELEASE_CHANNEL != 'staging' }}
        uses: ./.github/actions/cn_release
        with:
          cmd: upload
          app: ${{ env.CN_APPLICATION }}
          key: ${{ secrets.CN_API_KEY }}
          channel: ${{ env.RELEASE_CHANNEL }}
          framework: tauri
          working-directory: ./apps/desktop
      - if: ${{ env.RELEASE_CHANNEL == 'staging' && matrix.platform == 'macos' }}
        uses: actions/upload-artifact@v4
        with:
          name: hyprnote-staging-${{ matrix.target }}
          path: apps/desktop/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          retention-days: 3
      - if: ${{ env.RELEASE_CHANNEL == 'staging' && matrix.platform == 'windows' }}
        uses: actions/upload-artifact@v4
        with:
          name: hyprnote-staging-${{ matrix.target }}
          path: |
            apps/desktop/src-tauri/target/${{ matrix.target }}/release/bundle/msi/*.msi
            apps/desktop/src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe
          retention-days: 3
  publish:
    if: ${{ ((github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'desktop_'))) }}
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cn_release
        with:
          cmd: publish
          app: ${{ env.CN_APPLICATION }}
          key: ${{ secrets.CN_API_KEY }}
          channel: ${{ env.RELEASE_CHANNEL }}
          framework: tauri
          working-directory: ./apps/desktop
